config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  resources :poles
  resources :fiches
  resources :pages
  resources :camps, only: :create
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/advocacy.rb
class Advocacy < ApplicationRecord
  belongs_to :pole
  has_one_attached :document
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/camp.rb
class Camp < ApplicationRecord
end

app/models/fiche.rb
class Fiche < ApplicationRecord
  belongs_to :pole

  has_one_attached :document_1
  has_one_attached :document_2
  has_one_attached :document_3
end

app/models/page.rb
class Page < ApplicationRecord
  has_one_attached :document_1
  has_one_attached :document_2
  has_one_attached :document_3
end

app/models/person.rb
class Person < ApplicationRecord
  belongs_to :pole
end

app/models/pole.rb
class Pole < ApplicationRecord
  has_many :fiches, dependent: :destroy, class_name: 'Fiche'
  has_many :reports, dependent: :destroy
  has_many :advocacies, dependent: :destroy

  has_one_attached :document_1
  has_one_attached :document_2
  has_one_attached :document_3
end

app/models/post.rb
class Post < ApplicationRecord
  enum for: %w(obs camps blog)

  has_one_attached :document_1
  has_one_attached :document_2
  has_one_attached :document_3
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :pole
  has_one_attached :document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/camps_controller.rb
class CampsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    Camp.create!(params[:camp].permit!)

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/fiches_controller.rb
class FichesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @fiches = Fiche.pluck(:location, :latitude, :longitude)
    render(json: @fiches)
  end

  def show
    @fiche = Fiche.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def search
    @q = Fiche.search(params[:q])
    @fiches = @q.result
  end

  def show
    if params[:id] == 'search'
      @q = Fiche.search(params[:q])
      @fiches = @q.result
      return render('search')
    end

    @page = Page.find_by(slug: params[:id])

    if !@page
      return render(params[:id])
    end
  end
end

app/controllers/poles_controller.rb
class PolesController < ApplicationController
  skip_before_action :verify_authenticity_token

  def show
    @pole = Pole.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def google_map(center, size = "300x300")
    "https://maps.googleapis.com/maps/api/staticmap?center=#{center}&size=#{}&zoom=17"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/camps/create.js.erb
$('form.new_camp').not(':button, :submit, :reset, :hidden').val('').removeAttr('checked').removeAttr('selected')
$('.new_camp_created').show()

app/views/fiches/show.html.haml
%br/
%br/
.container
  %h3 #{@fiche.location} — #{@fiche.pole.name}
  %br/
  = (@fiche.description || '<p>Aucune description renseignée.</p>')&.html_safe
  - if @fiche.document_1.present?
    = link_to(@fiche.document_1_name || 'Télécharger Document 1', url_for(@fiche.document_1), class: 'btn btn-dark')
  - if @fiche.document_2.present?
    = link_to(@fiche.document_2_name || 'Télécharger Document 2', url_for(@fiche.document_2), class: 'btn btn-dark')
  - if @fiche.document_3.present?
    = link_to(@fiche.document_3_name || 'Télécharger Document 3', url_for(@fiche.document_3), class: 'btn btn-dark')
  - if @fiche.document_1.present? || @fiche.document_2.present? || @fiche.document_3.present?
    %br/
  %br/
  %br/
  = image_tag("https://maps.googleapis.com/maps/api/staticmap?center=#{[@fiche.latitude, @fiche.longitude].join(',')}&zoom=6&size=600x200&key=AIzaSyB-VE7BEdCw6S_613eERdgqoaiLYR7a7T0&region=MA&scale=2&markers=color:red|#{[@fiche.latitude, @fiche.longitude].join(',')}")

app/views/home/index.html.haml
#map
%div.div_orange div text 
 

%div{style: 'padding: 20px 0px; text-align: center; font-size: 24px; color: #29328A; font-weight: bold'}
  %div.cirlce_div 
    %br/
    %span.counter{style: "font-weight: bold; color: #fff; font-size: 32px"}= Fiche.count
    %br/
    Camps Observés
  %div.cirlce_div 
    %br/ 
    %span.counter{style: "font-weight: bold; color: #fff; font-size: 32px;margin-top:1%"}= Fiche.pluck(:country).uniq.compact.count
    %br/
    Pays 
  %div.cirlce_div
    %br/ 
    %span.counter{style: "font-weight: bold; color: #fff; font-size: 32px"}= Person.count
    %br/
    Contributeurs et Contributrices
 
  
 
:css
  .ais-geo-search--control {
    display: none;
  }

  #map {
    position: relative;
  }

app/views/pages/actualite_camps.html.haml
%br/
%br/
.container
  %h3 Actualité des Camps
  %br/
  - Post.camps.order(created_at: :desc).each do |post|
    %h4= post.name
    %p= post.content.html_safe
    - if post.document_1.present?
      = link_to(post.document_1_name || 'Télécharger Document 1', url_for(post.document_1), class: 'btn', style: 'background-color: lightgray')
    - if post.document_2.present?
      = link_to(post.document_2_name || 'Télécharger Document 2', url_for(post.document_2), class: 'btn', style: 'background-color: lightgray')
    - if post.document_3.present?
      = link_to(post.document_3_name || 'Télécharger Document 3', url_for(post.document_3), class: 'btn', style: 'background-color: lightgray')
    - if post.document_1.present? || post.document_2.present? || post.document_3.present?
      %br/
    %br/
    %hr/
    %br/

app/views/pages/actualite_observatoire.html.haml
%br/
%br/
.container
  %h3 Actualité de l’Observatoire
  %br/
  - Post.obs.order(created_at: :desc).each do |post|
    %h4= post.name
    %p= post.content.html_safe
    - if post.document_1.present?
      = link_to(post.document_1_name || 'Télécharger Document 1', url_for(post.document_1), class: 'btn', style: 'background-color: lightgray')
    - if post.document_2.present?
      = link_to(post.document_2_name || 'Télécharger Document 2', url_for(post.document_2), class: 'btn', style: 'background-color: lightgray')
    - if post.document_3.present?
      = link_to(post.document_3_name || 'Télécharger Document 3', url_for(post.document_3), class: 'btn', style: 'background-color: lightgray')
    - if post.document_1.present? || post.document_2.present? || post.document_3.present?
      %br/
    %br/
    %hr/
    %br/

app/views/pages/blog.html.haml
%br/
%br/
.container
  %h3 Blog
  %br/
  - Post.blog.order(created_at: :desc).each do |post|
    %h4= post.name
    %p= post.content.html_safe
    - if post.document_1.present?
      = link_to(post.document_1_name || 'Télécharger Document 1', url_for(post.document_1), class: 'btn', style: 'background-color: lightgray')
    - if post.document_2.present?
      = link_to(post.document_2_name || 'Télécharger Document 2', url_for(post.document_2), class: 'btn', style: 'background-color: lightgray')
    - if post.document_3.present?
      = link_to(post.document_3_name || 'Télécharger Document 3', url_for(post.document_3), class: 'btn', style: 'background-color: lightgray')
    - if post.document_1.present? || post.document_2.present? || post.document_3.present?
      %br/
    %br/
    %hr/
    %br/

app/views/pages/camps.html.haml
%br/
%br/
.container
  %h4 Camps
  %br/
  %h5 Définitions et terminologies
  %p Document en attente.

  %br/
  %h5 le pôle Europe (13 camps)
  %p Italie (5 camps), Grèce (6 camps), Serbie (2)

  %br/
  %h5 le pôle Amériques (19)
  %p Colombie (5), Costa-Rica (3), Mexique (2), Panama (2), Belize (1), Haïti (1), Nicaragua (1), Guatemala (2), Honduras (1), Equateur (1)

  %br/
  %h5 le pôle Afrique (43)
  %p Rwanda (5), Togo (1), Niger (4), Ethiopie (3), Ouganda (2), Burkina-Faso (2), Libéria (1), Tchad (7), Kenya (2), Cameroun (4), Malawi (2), République Démocratique du Congo (4), Zimbabwe (1) Ghana (3) Soudan (1), Tanzanie (1)

  %br/
  %h5 le pôle Asie et Pacifique (11 camps)
  %p Pakistan (3) , Thaïlande (3), Bangladesh (2), Iran (1), Birmanie (2)

  %br/
  %h5 le pôle Afrique du Nord et Moyen-Orient (34)
  %p
    Territoires palestiniens (6), Liban (11), Libye (2), Jordanie (2), Algérie (2), Turquie (2), Irak (1), Syrie (5), Mauritanie (1), Tunisie (1), Yémen (1)

  %br/
  %h4 Suggérer un camps
  %p
    Merci de renseigner le formulaire ci-dessous pour nous suggérer un nouveau camps.

  .new_camp_created{style: 'display: none;'}
    .alert.alert-success
      %h4{style: "padding: 10px; margin: 0;"} Merci, votre message a bien été envoyé.
    %br/

  = simple_form_for Camp.new, url: camps_path, remote: true do |form|
    = form.input :name, label: 'Nom du camps'
    = form.input :country, label: 'Pays'
    = form.input :url, label: 'Lien web'
    = form.submit 'Envoyer', class: 'btn btn-dark'
  %br/
  %br/

app/views/pages/search.html.haml
%br/
%br/
.container
  %h3 Rechercher
  %br/
  = simple_form_for @q, url: page_path(:search), method: :get do |f|
    = f.input :location_or_country_cont, as: :string, label: false, input_html: { placeholder: 'Par ville, pays ou addresse...' }
    %br/
    - @fiches.each do |fiche|
      %h5= link_to("#{fiche.location} — #{fiche.pole.name}", fich_path(fiche))
      %p
        Pays :
        = fiche.country
      %br/
    %br/
    = f.submit('Rechercher', class: "btn nav-link", style: "background: #37a9e1; color: white;")

app/views/pages/show.html.haml
%br/
%br/
.container
  %h4= @page.name
  - if @page.document_1.present? || @page.document_2.present? || @page.document_3.present?
    %br/
  - if @page.document_1.present?
    = link_to(@page.document_1_name || 'Télécharger Document 1', url_for(@page.document_1), class: 'btn btn-dark')
  - if @page.document_2.present?
    = link_to(@page.document_2_name || 'Télécharger Document 2', url_for(@page.document_2), class: 'btn btn-dark')
  - if @page.document_3.present?
    = link_to(@page.document_3_name || 'Télécharger Document 3', url_for(@page.document_3), class: 'btn btn-dark')
  - if @page.document_1.present? || @page.document_2.present? || @page.document_3.present?
    %br/
    %br/
  %br/
  = @page.content.html_safe

app/views/poles/show.html.haml
%br/
%br/
.container
  %h3= @pole.name
  %br/
  = (@pole.description || '<p>Aucune description renseignée.</p>')&.html_safe
  - if @pole.document_1.present?
    = link_to(@pole.document_1_name || 'Télécharger Document 1', url_for(@pole.document_1), class: 'btn btn-dark')
  - if @pole.document_2.present?
    = link_to(@pole.document_2_name || 'Télécharger Document 2', url_for(@pole.document_2), class: 'btn btn-dark')
  - if @pole.document_3.present?
    = link_to(@pole.document_3_name || 'Télécharger Document 3', url_for(@pole.document_3), class: 'btn btn-dark')
  - if @pole.document_1.present? || @pole.document_2.present? || @pole.document_3.present?
    %br/
    %br/
  %br/
  .row
    .col-md-4
      %div{style: "background-color: #2daae1; color: white; font-size: 20px; padding: 10px 20px; text-align: center"} FICHES – CAMPS
      - @pole.fiches.group_by(&:country).each do |country, fiches|
        .card
          .card-header{id: country}
            %h5.mb-0
              %span.btn
                #{country} (#{ pluralize(fiches.count, 'camps') })
          .card-body
            %ul
              - fiches.each do |fiche|
                %li= link_to(fiche.location, fich_path(fiche))

    .col-md-4
      %div{style: "background-color: #2daae1; color: white; font-size: 20px; padding: 10px 20px; text-align: center"} RAPPORTS
      - @pole.reports.each do |report|
        .card
          .card-header
            %h5.mb-0
              %span.btn
                = report.name
          .card-body
            = report.description
            %br/
            %br/
            = link_to('Télécharger', rails_blob_path(report.document, disposition: "attachment"), style: "color: #29328a", class: 'btn btn-warning')

    .col-md-4
      %div{style: "background-color: #2daae1; color: white; font-size: 20px; padding: 10px 20px; text-align: center"} PLAIDOYER
      - @pole.advocacies.each do |advocacy|
        .card
          .card-header
            %h5.mb-0
              %span.btn
                = advocacy.name
          .card-body
            = advocacy.description
            %br/
            %br/
            = link_to('Télécharger', rails_blob_path(advocacy.document, disposition: "attachment"), style: "color: #29328a", class: 'btn btn-warning')